name: Deploy on GitHub Pages
on:
  push:
    branches:
      - master
      - main
      - dev
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'

env:
  ONTOLOGY_NAME: microscopy
  ONTOLOGY_IRI: https://w3id.org/emmo/domain/microscopy

permissions:
  contents: write


jobs:
  deploy-on-ghpages:
    #concurrency: ci-${{ github.ref }}  # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install EMMOntoPy
      run: |
        pip install --upgrade pip
        pip install git+https://github.com/emmo-repo/EMMOntoPy.git@master

    - name: Install ROBOT
      run: |
        mkdir bin
        wget -nv https://github.com/ontodev/robot/releases/download/v1.9.6/robot.jar
        mv robot.jar bin/.
        curl https://raw.githubusercontent.com/ontodev/robot/master/bin/robot > bin/robot
        chmod +x bin/robot
        ls -l bin/

    - name: Create dependencies, squashed and inferred ontologies
      run: |
        mkdir build
        cp README.md build/.
        ontoconvert \
            -saw \
            --namespace="emmo:https://w3id.org/emmo#" \
            ${ONTOLOGY_NAME}-dependencies.ttl \
            build/${ONTOLOGY_NAME}-dependencies.ttl
        ontoconvert \
            -sawe \
            --base-iri="${ONTOLOGY_IRI}#" \
            --iri="${ONTOLOGY_IRI}" \
            ${ONTOLOGY_NAME}.ttl \
            build/${ONTOLOGY_NAME}.ttl
        bin/robot reason --reasoner HermiT --input build/${ONTOLOGY_NAME}.ttl --output build/${ONTOLOGY_NAME}-inferred.ttl

        # HermiT (when run via EMMOntoPy) doesn't support custom datatypes. Use ROBOT instead
        #ontoconvert \
        #    -sawe \
        #    --base-iri="${ONTOLOGY_IRI}#" \
        #    --iri="${ONTOLOGY_IRI}" \
        #    --infer=HermiT \
        #    ${ONTOLOGY_NAME}.ttl \
        #    build/${ONTOLOGY_NAME}-inferred.ttl

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        branch: gh-pages
        clean: false
        single-commit: true
